# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NCymyFgtdlEkkFRgzIN6xok3nCzA8DV9
"""

import pandas as pd
import numpy as np

bangladesh_df = pd.read_csv('bangla.csv')
canada_df = pd.read_csv('canada.csv')
britain_df = pd.read_csv('britain.csv')
india = pd.read_csv('india.csv')
russia_df = pd.read_csv('russia.csv')
china_df = pd.read_csv('china.csv')

print(bangladesh_df.info() , canada_df.info() , britain_df.info() ,
      russia_df.info() , china_df.info())

print(bangladesh['gdp'].values)

print(bangladesh.head())

print(bangladesh)

#Pipeline
from sklearn.model_selection import train_test_split
from sklearn.base import TransformerMixin, BaseEstimator
from sklearn.preprocessing import StandardScaler,Imputer
from sklearn.pipeline import Pipeline
class DataFrameSelector(BaseEstimator,TransformerMixin):
    def __init__(self,attribute):
        self.attributes = attribute
    def fit(self, X , y = None):
        return self
    def transform(self,X):
        return X[self.attributes].values

num_attribs = [ 'wind_cons' , 'nuc_con' , 'hydro_cons'  ,  'gdp', 'bca' ,  'le' , 'tmg']


num_pipeline = Pipeline([('imp',Imputer(strategy='median')),('std',StandardScaler())])
X = bangladesh_df.drop(['emmissions'] , axis = 1)
y = bangladesh_df['emmissions']
X_train,X_test,y_train,y_test = train_test_split(X , y , test_size=0.33 , random_state=42 )

x_train_transformed = num_pipeline.fit_transform(X_train)



from sklearn.linear_model import LinearRegression

lin_model = LinearRegression()
lin_model.fit(x_train_transformed,y_train)

X_test_prepared = num_pipeline.fit_transform(X_test)
predictions = lin_model.predict(X_test_prepared)

from sklearn.metrics import mean_squared_error

print(np.sqrt(mean_squared_error(predictions,y_test)))

corr = bangladesh.corr()

import seaborn as sns
print(sns.heatmap(corr))

